def two_pointers_converging(arr):
    l, r = 0, len(arr) - 1
    result = ...
    while l < r:
        ...
        ...
        ...
        if ...:
            l += 1
        else:
            r -= 1
    return result
